select * from Servicios

DELETE FROM Servicios
INSERT INTO [dbo].[Servicios](NombreServicio, DescripcionServicio)
VALUES ('Plasma Rico en Plaquetas (PRP)','Es un tratamiento regenerativo que consiste en extraer una pequeña cantidad de sangre del paciente, procesarla para separar el plasma con mayor concentración de plaquetas y aplicarlo mediante microinyecciones en el rostro o cuero cabelludo. Este plasma estimula la producción de colágeno, mejora la firmeza y elasticidad de la piel, y ayuda a regenerar tejidos, ideal para combatir los signos de envejecimiento o la caída del cabello.'),
	   ('Rejuvenecimiento Facial','Tratamiento enfocado en revitalizar la piel del rostro, mejorar su textura y tono, y disminuir arrugas o líneas de expresión. Se realiza con técnicas como microagujas (dermapen), masajes faciales, aplicación de sueros nutritivos y activos reafirmantes, que estimulan la regeneración celular sin usar aparatología invasiva ni láser.'),
	   ('Limpieza Facial Profunda','Procedimiento estético que busca eliminar impurezas, puntos negros, células muertas y exceso de grasa acumulada en el rostro. Incluye pasos como desmaquillado, exfoliación, extracción manual, mascarillas hidratantes o calmantes y protector solar. Es ideal para mantener una piel limpia, oxigenada y saludable.'),
	   ('Despigmentación Facial','Técnica que trabaja sobre manchas oscuras causadas por el sol, acné o alteraciones hormonales. Se utilizan productos despigmentantes tópicos, peelings suaves o activos naturales que ayudan a unificar el tono de la piel, reducir la apariencia de manchas y mejorar la luminosidad del rostro sin recurrir a procedimientos con láser.'),
	   ('Lifting de Pestañas','Tratamiento que realza las pestañas naturales mediante la aplicación de un gel que las alisa y curva desde la raíz. El procedimiento da un efecto de mayor longitud, volumen y elevación sin necesidad de utilizar rizador ni extensiones. Se complementa con tinte para intensificar su color, logrando una mirada más expresiva y abierta.'),
	   ('Masaje Reductor','Masaje manual con movimientos intensos y rítmicos que buscan estimular la circulación, movilizar los depósitos de grasa localizada y favorecer la eliminación de líquidos retenidos. Suele aplicarse en abdomen, piernas o brazos y se complementa con cremas termogénicas. Es ideal para moldear la figura y reducir medidas de forma progresiva.'),
	   ('Levantamiento de Glúteos','Técnica estética no invasiva que utiliza masajes, ventosas o aparatología de vacío para estimular la musculatura, mejorar la circulación y tonificar la zona glútea. Se busca reafirmar la piel y dar un efecto visual de mayor volumen, firmeza y redondez, sin recurrir a intervenciones quirúrgicas.'),
	   ('Terapia de Cupping (Ventosas)','Tratamiento basado en la aplicación de ventosas que generan succión sobre la piel, lo que ayuda a mejorar la circulación, eliminar toxinas, relajar la musculatura y estimular el drenaje linfático. Se utiliza tanto con fines terapéuticos (para aliviar tensión) como estéticos (en tratamientos reductores y reafirmantes).')